/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as TravelPlannerRouteImport } from './routes/travel-planner'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CheckoutTripIdRouteImport } from './routes/checkout.$tripId'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelPlannerRoute = TravelPlannerRouteImport.update({
  id: '/travel-planner',
  path: '/travel-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTripIdRoute = CheckoutTripIdRouteImport.update({
  id: '/checkout/$tripId',
  path: '/checkout/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bookings': typeof BookingsRoute
  '/travel-planner': typeof TravelPlannerRoute
  '/wishlist': typeof WishlistRoute
  '/checkout/$tripId': typeof CheckoutTripIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bookings': typeof BookingsRoute
  '/travel-planner': typeof TravelPlannerRoute
  '/wishlist': typeof WishlistRoute
  '/checkout/$tripId': typeof CheckoutTripIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/bookings': typeof BookingsRoute
  '/travel-planner': typeof TravelPlannerRoute
  '/wishlist': typeof WishlistRoute
  '/checkout/$tripId': typeof CheckoutTripIdRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/bookings'
    | '/travel-planner'
    | '/wishlist'
    | '/checkout/$tripId'
    | '/trips/$tripId'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/bookings'
    | '/travel-planner'
    | '/wishlist'
    | '/checkout/$tripId'
    | '/trips/$tripId'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/bookings'
    | '/travel-planner'
    | '/wishlist'
    | '/checkout/$tripId'
    | '/trips/$tripId'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookingsRoute: typeof BookingsRoute
  TravelPlannerRoute: typeof TravelPlannerRoute
  WishlistRoute: typeof WishlistRoute
  CheckoutTripIdRoute: typeof CheckoutTripIdRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-planner': {
      id: '/travel-planner'
      path: '/travel-planner'
      fullPath: '/travel-planner'
      preLoaderRoute: typeof TravelPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$tripId': {
      id: '/checkout/$tripId'
      path: '/checkout/$tripId'
      fullPath: '/checkout/$tripId'
      preLoaderRoute: typeof CheckoutTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookingsRoute: BookingsRoute,
  TravelPlannerRoute: TravelPlannerRoute,
  WishlistRoute: WishlistRoute,
  CheckoutTripIdRoute: CheckoutTripIdRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
